TW\frontOfficeBundle\Entity\Domaine:
    type: entity
    table: domaine
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToMany:
        idetablissement:
            targetEntity: Etablissement
            cascade: {  }
            mappedBy: iddomaine
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
