TW\frontOfficeBundle\Entity\Lieu:
    type: entity
    table: lieu
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ville:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
