Commentaire:
    pattern:  /
    defaults: { _controller: "TWfrontOfficeBundle:Commentaire:index" }

Commentaire_show:
    pattern:  /{id}/show
    defaults: { _controller: "TWfrontOfficeBundle:Commentaire:show" }

Commentaire_new:
    pattern:  /new
    defaults: { _controller: "TWfrontOfficeBundle:Commentaire:new" }

Commentaire_create:
    pattern:  /create/{reclamation_id}
    defaults: { _controller: "TWfrontOfficeBundle:Commentaire:create" }
    requirements: { _method: post }

Commentaire_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TWfrontOfficeBundle:Commentaire:edit" }

Commentaire_update:
    pattern:  /{id}/update
    defaults: { _controller: "TWfrontOfficeBundle:Commentaire:update" }
    requirements: { _method: post|put }

Commentaire_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TWfrontOfficeBundle:Commentaire:delete" }
    requirements: { _method: post|delete }
